package kg.geektech.game.players;

public enum SuperAbility {
    HEAL, BOOST, CRITICAL_DAMAGE, SAVE_DAMAGE_AND_REVERT, BOSS_CANT_HIT,GOLEM, PRIZYV_ANGEL_AND_VORON,ANTMAN, DEAD_AND_HELP, HACKER, DEKU, AURORA, MAKE_A_JOKE
}
